csv 파일로 변환

In [ ]:
from bs4 import BeautifulSoup


import requests
import pandas as pd



url1 = "https://colory.mooo.com/ranking"
url2 = "https://m.blog.naver.com/SectionPostSearch.naver?orderType=sim&searchValue="



headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
}

response = requests.get(url1, headers=headers)

# html = driver.page_source
soup = BeautifulSoup(response.text, "html.parser")


for index in range(1,9):
  df = pd.DataFrame({'매장':[],'테마':[],'평점':[],'리뷰수':[], '블로그 리뷰':[]})

  location = soup.find(id='theme-button-'+str(index))
  location_list = location.find_all('tr')
  location_name = location.find('h5').text
  file_name = location_name + ".csv"
  for i in location_list:
    list = []
    elements = i.find_all('td')
    a = df.shape[0]
    for element in elements:
      if element.string == None:
        pass
      else:
        list.append(element.string)

    if len(list) == 0:
        pass
    else:
      if len(list) == 4:
        pass
      else:
        list.remove(list[0])
      new_url = url2 + list[0] +' '+ list[1]
      list.append(new_url)
      df.loc[a] = list

  df.to_csv(file_name, index=False)

In [ ]:
df

,매장,테마,평점,리뷰수,블로그 리뷰
0,한국 방탈출 교육원,소울리아,8.87,153,https://m.blog.naver.com/SectionPostSearch.nav...
1,제로월드 X 롯데월드,바람,8.75,190,https://m.blog.naver.com/SectionPostSearch.nav...
2,쿠쿠룸242,신비로운 관찰생활 리본,8.39,519,https://m.blog.naver.com/SectionPostSearch.nav...
3,쿠쿠룸242,개미는 뚠뚠 오늘도 뚠뚠,8.37,251,https://m.blog.naver.com/SectionPostSearch.nav...
4,머더파커 잠실점,정육각형,8.35,584,https://m.blog.naver.com/SectionPostSearch.nav...
...,...,...,...,...,...
95,큐브 이스케이프 잠실점,로미오 포인트,3.99,79,https://m.blog.naver.com/SectionPostSearch.nav...
96,탈출브라더스,미녀와 야수2,3.86,44,https://m.blog.naver.com/SectionPostSearch.nav...
97,셜록홈즈 잠실1호점,미대교수의 비밀,3.76,92,https://m.blog.naver.com/SectionPostSearch.nav...
98,셜록홈즈 잠실1호점,산속의 여인,3.74,87,https://m.blog.naver.com/SectionPostSearch.nav...
99,셜록홈즈 잠실1호점,웨딩크루즈 살인사건,3.56,71,https://m.blog.naver.com/SectionPostSearch.nav...

전체 매장 통합

In [ ]:
import pandas as pd

market_list = ['강남','강북','건대','대학로','서울(기타)','신림','신촌','홍대']

# 빈 딕셔너리 생성
market_data = {}

# 각 파일을 불러와서 딕셔너리에 저장
for market in market_list:
    market_data[market] = pd.read_csv(f'{market}.csv')

# 모든 데이터를 합치기
all_data = pd.concat(market_data.values(), ignore_index=True)
all_data = all_data.sort_values(by='평점', ascending=False, ignore_index=True)
all_data
# csv 파일로 저장
all_data.to_csv('combined_data.csv', index=False)

난이도 긁어오기

In [ ]:
from bs4 import BeautifulSoup


import requests
import pandas as pd



url1 = "https://colory.mooo.com/catalogue"



headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
}

response = requests.get(url1, headers=headers)

soup = BeautifulSoup(response.text, "html.parser")


for index in range(1,9):
  df = pd.DataFrame({'테마':[],'평점':[],'난이도':[], '리뷰수':[]})

  location = soup.find(id='theme-button-'+str(index))
  location_list = location.find_all('td')
  location_name = location.find('h5').text
  file_name = location_name + "_난이도.csv"

  list = []
  i= 0
  while i < len(location_list):
    a = df.shape[0]
    if location_list[i]['class'][0] == 'info-1':
      i=i+1
    else:
      if location_list[i]['class'][0] == 'info-5':
        list.append(location_list[i].text)
        df.loc[a]=list
        list = []
        i=i+1
      else:
        list.append(location_list[i].text)
        i = i+1

  print(df.info())
  df.to_csv(file_name, index=False)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 159 entries, 0 to 158
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   테마      159 non-null    object
 1   평점      159 non-null    object
 2   난이도     159 non-null    object
 3   리뷰수     159 non-null    object
dtypes: object(4)
memory usage: 6.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 87 entries, 0 to 86
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   테마      87 non-null     object
 1   평점      87 non-null     object
 2   난이도     87 non-null     object
 3   리뷰수     87 non-null     object
dtypes: object(4)
memory usage: 3.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 154 entries, 0 to 153
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   테마      154 non-null    object
 1   평점      154 non-null    object
 2   난이도     154 non-null    object
 3   리뷰수     154 non-null    object
dtypes: object(4)
memory usage: 6.0+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 52 entries, 0 to 51
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   테마      52 non-null     object
 1   평점      52 non-null     object
 2   난이도     52 non-null     object
 3   리뷰수     52 non-null     object
dtypes: object(4)
memory usage: 2.0+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 54 entries, 0 to 53
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   테마      54 non-null     object
 1   평점      54 non-null     object
 2   난이도     54 non-null     object
 3   리뷰수     54 non-null     object
dtypes: object(4)
memory usage: 2.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   테마      30 non-null     object
 1   평점      30 non-null     object
 2   난이도     30 non-null     object
 3   리뷰수     30 non-null     object
dtypes: object(4)
memory usage: 1.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 37 entries, 0 to 36
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   테마      37 non-null     object
 1   평점      37 non-null     object
 2   난이도     37 non-null     object
 3   리뷰수     37 non-null     object
dtypes: object(4)
memory usage: 1.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   테마      100 non-null    object
 1   평점      100 non-null    object
 2   난이도     100 non-null    object
 3   리뷰수     100 non-null    object
dtypes: object(4)
memory usage: 3.9+ KB
None

서울 전체 난이도

In [ ]:
import pandas as pd

market_list = ['강남','강북','건대','대학로','서울(기타)','신림','신촌','홍대']

# 빈 딕셔너리 생성
market_data = {}

# 각 파일을 불러와서 딕셔너리에 저장
for market in market_list:
    market_data[market] = pd.read_csv(f'{market}_난이도.csv')

# 모든 데이터를 합치기
all_data = pd.concat(market_data.values(), ignore_index=True)
all_data = all_data.sort_values(by='평점', ascending=False, ignore_index=True)
all_data
# csv 파일로 저장
all_data.to_csv('combined_data_난이도.csv', index=False)

랭킹, 난이도 합치기

In [ ]:
market_list = ['강남','강북','건대','대학로','서울(기타)','신림','신촌','홍대', 'combined_data']


for market in market_list:

    location =  pd.read_csv(f'{market}.csv')
    difficulty = pd.read_csv(f'{market}_난이도.csv')

    theme_loc = location['테마']

    location['난이도'] = 0

    for i in theme_loc:
      b = difficulty.loc[difficulty['테마']==i]
      b= b['난이도'].values
      location.loc[location['테마']==i,'난이도'] = b[0]

    location.info()

    location.to_csv(f'{market}_최종.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   매장      159 non-null    object
 1   테마      159 non-null    object
 2   평점      159 non-null    float64
 3   리뷰수     159 non-null    int64
 4   블로그 리뷰  159 non-null    object
 5   난이도     159 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 7.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   매장      30 non-null     object
 1   테마      30 non-null     object
 2   평점      30 non-null     float64
 3   리뷰수     30 non-null     int64
 4   블로그 리뷰  30 non-null     object
 5   난이도     30 non-null     int64
dtypes: float64(1), int64(2), object(3)
memory usage: 1.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   매장      87 non-null     object
 1   테마      87 non-null     object
 2   평점      87 non-null     float64
 3   리뷰수     87 non-null     int64
 4   블로그 리뷰  87 non-null     object
 5   난이도     87 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   매장      54 non-null     object
 1   테마      54 non-null     object
 2   평점      54 non-null     float64
 3   리뷰수     54 non-null     int64
 4   블로그 리뷰  54 non-null     object
 5   난이도     54 non-null     int64
dtypes: float64(1), int64(2), object(3)
memory usage: 2.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   매장      100 non-null    object
 1   테마      100 non-null    object
 2   평점      100 non-null    float64
 3   리뷰수     100 non-null    int64
 4   블로그 리뷰  100 non-null    object
 5   난이도     100 non-null    int64
dtypes: float64(1), int64(2), object(3)
memory usage: 4.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   매장      37 non-null     object
 1   테마      37 non-null     object
 2   평점      37 non-null     float64
 3   리뷰수     37 non-null     int64
 4   블로그 리뷰  37 non-null     object
 5   난이도     37 non-null     int64
dtypes: float64(1), int64(2), object(3)
memory usage: 1.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   매장      52 non-null     object
 1   테마      52 non-null     object
 2   평점      52 non-null     float64
 3   리뷰수     52 non-null     int64
 4   블로그 리뷰  52 non-null     object
 5   난이도     52 non-null     int64
dtypes: float64(1), int64(2), object(3)
memory usage: 2.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   매장      154 non-null    object
 1   테마      154 non-null    object
 2   평점      154 non-null    float64
 3   리뷰수     154 non-null    int64
 4   블로그 리뷰  154 non-null    object
 5   난이도     154 non-null    int64
dtypes: float64(1), int64(2), object(3)
memory usage: 7.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 673 entries, 0 to 672
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   매장      673 non-null    object
 1   테마      673 non-null    object
 2   평점      673 non-null    float64
 3   리뷰수     673 non-null    int64
 4   블로그 리뷰  673 non-null    object
 5   난이도     673 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 31.7+ KB

In [ ]:
import pandas as pd

market_list = ['강남','강북','건대','대학로','서울(기타)','신림','신촌','홍대']

# 빈 딕셔너리 생성
market_data = {}

# 각 파일을 불러와서 딕셔너리에 저장
for market in market_list:
    market_data[market] = pd.read_csv(f'{market}_최종.csv')
    market_data[market]['지역'] = market

# 모든 데이터를 합치기
all_data = pd.concat(market_data.values(), ignore_index=True)
all_data = all_data.sort_values(by='평점', ascending=False, ignore_index=True)
all_data
# csv 파일로 저장
all_data.to_csv('combined_data_지역추가.csv', index=False)

-------------------------------
# 전체 한번에 긁어오기

전체 지역 파일 만들기 (지점, 테마, 평점, 리뷰수, 블로그 리뷰, 지역)

In [ ]:
from bs4 import BeautifulSoup


import requests
import pandas as pd



url1 = "https://colory.mooo.com/ranking"
url2 = "https://m.blog.naver.com/SectionPostSearch.naver?orderType=sim&searchValue="



headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
}

response = requests.get(url1, headers=headers)

# html = driver.page_source
soup = BeautifulSoup(response.text, "html.parser")

df = pd.DataFrame({'매장':[],'테마':[],'평점':[],'리뷰수':[], '블로그 리뷰':[], '지역':[]})

for index in range(1,27):
  location = soup.find(id='theme-button-'+str(index))
  location_list = location.find_all('tr')
  location_name = location.find('h5').text
  file_name = location_name + ".csv"

  #매장부터 리뷰 수까지
  for i in location_list:
    list = []
    elements = i.find_all('td')
    a = df.shape[0]
    for element in elements:
      if element.string == None:
        pass
      else:
        list.append(element.string)

    if len(list) == 0:
        pass
    else:
      if len(list) == 4:
        pass
      else:
        list.remove(list[0])

      #url 추가
      new_url = url2 + list[0] +' '+ list[1]
      list.append(new_url)

      #지역 추가
      list.append(location_name)

      #데이터프레임에 리스트 넣기
      df.loc[a] = list

print(df)
print(df.info())
#df.to_csv(file_name, index=False)

                   매장             테마    평점  리뷰수  \
0       키이스케이프 메모리컴퍼니    FILM BY BOB  9.66  175
1     키이스케이프 LOG_IN 1        머니머니패키지  9.63  484
2            제로월드 강남점             제로  9.62  679
3       키이스케이프 메모리컴퍼니  FILM BY STEVE  9.45  619
4       키이스케이프 메모리컴퍼니   FILM BY EDDY  9.39  708
...               ...            ...   ...  ...
1749        제주방탈출 제원점       신입사원 출근기  4.07   27
1750        제주방탈출 시청점           학교괴담  4.00    5
1751        제주방탈출 시청점          고흐의 방  3.67    6
1752        제주방탈출 시청점        위험한 레시피  3.60   10
1753        제주방탈출 제원점         저주받은 집  3.25    4

                                                 블로그 리뷰  지역
0     https://m.blog.naver.com/SectionPostSearch.nav...  강남
1     https://m.blog.naver.com/SectionPostSearch.nav...  강남
2     https://m.blog.naver.com/SectionPostSearch.nav...  강남
3     https://m.blog.naver.com/SectionPostSearch.nav...  강남
4     https://m.blog.naver.com/SectionPostSearch.nav...  강남
...                                                 ...  ..
1749  https://m.blog.naver.com/SectionPostSearch.nav...  제주
1750  https://m.blog.naver.com/SectionPostSearch.nav...  제주
1751  https://m.blog.naver.com/SectionPostSearch.nav...  제주
1752  https://m.blog.naver.com/SectionPostSearch.nav...  제주
1753  https://m.blog.naver.com/SectionPostSearch.nav...  제주

[1754 rows x 6 columns]
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1754 entries, 0 to 1753
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   매장      1754 non-null   object
 1   테마      1754 non-null   object
 2   평점      1754 non-null   object
 3   리뷰수     1754 non-null   object
 4   블로그 리뷰  1754 non-null   object
 5   지역      1754 non-null   object
dtypes: object(6)
memory usage: 95.9+ KB
None

In [ ]:
df.to_csv('all_location.csv', index=False)

전체 난이도 긁어오기

In [ ]:
from bs4 import BeautifulSoup


import requests
import pandas as pd



url1 = "https://colory.mooo.com/catalogue"



headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
}

response = requests.get(url1, headers=headers)

soup = BeautifulSoup(response.text, "html.parser")

df = pd.DataFrame({'테마':[],'평점':[],'난이도':[], '리뷰수':[]})

for index in range(1,27):
  location = soup.find(id='theme-button-'+str(index))
  location_list = location.find_all('td')
  location_name = location.find('h5').text
  file_name = location_name + "_난이도.csv"

  list = []
  i= 0
  while i < len(location_list):
    a = df.shape[0]
    if location_list[i]['class'][0] == 'info-1':
      i=i+1
    else:
      if location_list[i]['class'][0] == 'info-5':
        list.append(location_list[i].text)
        df.loc[a]=list
        list = []
        i=i+1
      else:
        list.append(location_list[i].text)
        i = i+1

print(df.head())
df.to_csv('all_location_난이도.csv', index=False)

                           테마    평점  난이도  리뷰수
0  검은마법사 (The Dark Enchanter)  8.67  ???    6
1                      마지막 일주  6.58    2  634
2          안녕하세요? 무엇을 도와드릴까요?  6.69    5  783
3                          야근  6.83    5  912
4                         첫만남  6.89    8  875

전체 지역 난이도 합치기

In [ ]:

location =  pd.read_csv('all_location.csv')
difficulty = pd.read_csv('all_location_난이도.csv')

theme_loc = location['테마']

location['난이도'] = 0

for i in theme_loc:
  b = difficulty.loc[difficulty['테마']==i]
  b= b['난이도'].values
  location.loc[location['테마']==i,'난이도'] = b[0]


location = location.sort_values(by='평점', ascending=False, ignore_index=True)
location = location[['매장','테마','평점','리뷰수', '블로그 리뷰','난이도', '지역']]
location.head(20)
location.to_csv('all_location_최종.csv', index=False)

id 추가 (평점, 기록 위함)

In [ ]:
import pandas as pd
from random import *

import numpy as np

# 1~45 중 중복 없이 6개 숫자 추출
numbers = np.random.choice(range(1, 2000), 1754, replace=False)

print(len(numbers) )

all_location = pd.read_csv('all_location.csv')
all_location['id'] = numbers
all_location.head()
all_location.to_csv('all_loaction+id.csv', index = False)

1754

# 리뷰수, 평점 업데이트

In [ ]:
#이전 데이터 불러오기
preData = pd.read_csv('all_location.csv', header=None)
#칼럼 추가
preData.columns = ['매장','테마','평점','리뷰수', '블로그 리뷰','난이도', '지역','id']
#새 데이터 불러오기
newData = pd.read_csv('all_location_최종.csv')

#업데이트 루프
for row in preData.iterrows():
  b = newData.loc[(newData['매장']==row[1]['매장']) & (newData['테마']==row[1]['테마'])]
  if len(b)==1:
    score = b['평점'].values
    review = b['리뷰수'].values
    preData.loc[(preData['매장']==row[1]['매장']) & (preData['테마']==row[1]['테마']), '평점'] = score[0]
    preData.loc[(preData['매장']==row[1]['매장']) & (preData['테마']==row[1]['테마']),'리뷰수'] = review[0]

In [ ]:
preData = preData.sort_values(by='평점', ascending=False, ignore_index=True)
preData.to_csv('all_location_update.csv', index=False)